import { NextResponse } from 'next/server';
import { getStoredData, saveStoredData } from '../../../lib/serverStore';

const INITIAL_EVIDENCE = [
  {
    id: 'ev-1',
    name: 'AWS_IAM_Password_Policy_Report_2026.pdf',
    type: 'CONFIG_REPORT',
    mimeType: 'application/pdf',
    fileSize: 420100,
    status: 'VALID',
    collectedAt: '2026-09-10',
    source: 'AWS',
    mappedControls: ['CC6.1', 'A.9.1.1', 'PR.AA-01'],
    content: `AWS IAM Password Policy Export
Generated by AWS Identity & Access Management Config Scanner

MinimumPasswordLength: 14
RequireSymbols: true
RequireNumbers: true
RequireUppercaseCharacters: true
RequireLowercaseCharacters: true
AllowUsersToChangePassword: true
ExpirePasswords: false
MaxPasswordAge: 90
PasswordReusePrevention: 5
HardExpiry: false

MFA ENFORCEMENT SUMMARY:
- Active across 100% of IAM Console Users via Okta SSO.
- Root account MFA: Hardware FIDO2 YubiKey Active.
- Inactive credentials deactivated automatically after 60 days.`,
    aiAnalysis: {
      status: 'COMPLIANT',
      confidence: 0.96,
      summary: 'Enforces 14-char min length, MFA requirement, and restricts reuse of previous 5 passwords in compliance with SOC 2 CC6.1.',
      gaps: [],
      recommendations: ['Maintain automated annual credential rotation drills.'],
      citations: [
        { document: 'AWS_IAM_Password_Policy_Report_2026.pdf', page: 1, text: 'RequireSymbols: true, MinimumPasswordLength: 14, MFA Enforcement: Active' },
      ],
    },
  },
  {
    id: 'ev-2',
    name: 'Information_Security_Policy_v3.2.docx',
    type: 'POLICY',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    fileSize: 1250000,
    status: 'UNDER_REVIEW',
    collectedAt: '2026-09-14',
    source: 'MANUAL',
    mappedControls: ['CC6.6', 'PR.DS-1', 'A.8.20'],
    content: `Corporate Information Security Policy - Section 4: Network & Cryptography
4.1 Perimeter Protection: All public endpoints must reside behind AWS WAF and CloudFront.
4.2 Data in Transit: TLS 1.2 or higher is mandatory for all inbound customer connections. Internal service-to-service communication within the VPC mesh uses mTLS.
4.3 Data at Rest: Sensitive customer data in PostgreSQL and S3 buckets is encrypted using AES-256 via AWS KMS customer-managed keys.`,
    aiAnalysis: {
      status: 'PARTIAL',
      confidence: 0.88,
      summary: 'Policy defines TLS 1.2+ requirement but requires explicit cipher suite constraint documentation for internal microservices.',
      gaps: ['Internal mTLS cipher suite whitelists need explicit documentation.'],
      recommendations: ['Update section 4.2 with approved TLS 1.3 cipher suites.'],
      citations: [
        { document: 'Information_Security_Policy_v3.2.docx', page: 14, text: 'Section 4.2: TLS 1.2 or higher is mandatory for all inbound customer connections.' },
      ],
    },
  },
  {
    id: 'ev-3',
    name: 'Q2_Penetration_Testing_Summary_Report.pdf',
    type: 'REPORT',
    mimeType: 'application/pdf',
    fileSize: 3450000,
    status: 'VALID',
    collectedAt: '2026-08-28',
    source: 'MANUAL',
    mappedControls: ['CC7.2', 'PR.IP-12'],
    content: `Executive Summary: External Network & Web Application Penetration Testing
Target: api.acme.com, auth.acme.com, app.acme.com
Conducted by: Bishop Fox Offensive Security Advisory
Date: August 2026

FINDINGS SYNOPSIS:
- Critical Findings: 0
- High Findings: 0
- Medium Findings: 2 (Both remediated in Sprint 28 and verified)
- Low Findings: 4 (Risk accepted / mitigated by WAF rate-limiting)

CONCLUSION:
The perimeter defense and modern identity stack withstand standard adversary simulations. Zero exploitable remote code execution or data exfiltration paths identified.`,
    aiAnalysis: {
      status: 'COMPLIANT',
      confidence: 0.99,
      summary: 'Third-party pen test completed by Bishop Fox; all identified Medium vulnerabilities remediated and validated by lead auditor.',
      gaps: [],
      recommendations: ['Schedule Q4 automated adversary simulation drill.'],
      citations: [
        { document: 'Q2_Penetration_Testing_Summary_Report.pdf', page: 3, text: 'Executive Summary: Zero High/Critical findings remaining post-retest.' },
      ],
    },
  },
];

const FILENAME = 'evidence.json';

export async function GET() {
  const evidence = getStoredData(FILENAME, INITIAL_EVIDENCE);
  return NextResponse.json(evidence);
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const evidence = getStoredData<any[]>(FILENAME, INITIAL_EVIDENCE);
    const newEvidence = {
      id: `ev-${Date.now()}`,
      name: body.name || 'Uploaded_Evidence_Document.pdf',
      type: body.type || 'DOCUMENT',
      mimeType: body.mimeType || 'application/pdf',
      fileSize: body.fileSize || 524288,
      status: body.status || 'VALID',
      collectedAt: new Date().toISOString().split('T')[0],
      source: body.source || 'MANUAL',
      mappedControls: body.mappedControls || ['CC6.1'],
      content: body.content || 'Evidence payload document content verified.',
      aiAnalysis: body.aiAnalysis || {
        status: 'COMPLIANT',
        confidence: 0.94,
        summary: 'Automated evaluation matches mapped control criteria with high confidence.',
        gaps: [],
        recommendations: ['Maintain regular update cycle.'],
        citations: [{ document: body.name || 'Document', page: 1, text: 'Attestation verified by autonomous engine.' }],
      },
    };
    evidence.unshift(newEvidence);
    saveStoredData(FILENAME, evidence);
    return NextResponse.json(newEvidence, { status: 201 });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 400 });
  }
}

export async function PATCH(req: Request) {
  try {
    const body = await req.json();
    const evidence = getStoredData<any[]>(FILENAME, INITIAL_EVIDENCE);
    let updatedItem: any = null;

    const updated = evidence.map((e) => {
      if (e.id === body.id) {
        updatedItem = { ...e, ...body };
        return updatedItem;
      }
      return e;
    });

    if (updatedItem) {
      saveStoredData(FILENAME, updated);
      return NextResponse.json({ success: true, evidence: updatedItem });
    }
    return NextResponse.json({ error: 'Evidence not found' }, { status: 404 });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 400 });
  }
}

export async function DELETE(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const id = searchParams.get('id');
    if (!id) return NextResponse.json({ error: 'Missing ID' }, { status: 400 });

    const evidence = getStoredData<any[]>(FILENAME, INITIAL_EVIDENCE);
    const filtered = evidence.filter((e) => e.id !== id);
    saveStoredData(FILENAME, filtered);
    return NextResponse.json({ success: true, id });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 400 });
  }
}
