/**
 * Lightweight Client-Side PDF Generator & Formatter
 * Produces valid PDF-1.4 documents and formatted print documents.
 */

export function generateSimplePDF(title: string, lines: string[], orgName: string = 'CloudSecure Enterprise'): Blob {
  const objects: string[] = [];
  
  objects.push('<< /Type /Catalog /Pages 2 0 R >>'); // 1
  objects.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>'); // 2
  objects.push('<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 595.28 841.89] /Contents 5 0 R >>'); // 3
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'); // 4

  let streamContent = `BT /F1 16 Tf 50 800 Td (${sanitizePDFText(title)}) Tj ET\n`;
  streamContent += `BT /F1 10 Tf 50 780 Td (Generated by ${sanitizePDFText(orgName)} AI-Compliance Platform - Confidential) Tj ET\n`;
  streamContent += `BT /F1 10 Tf 50 765 Td (------------------------------------------------------------------------------------------------) Tj ET\n`;

  let y = 745;
  for (const rawLine of lines) {
    if (y < 60) break; // stay within single-page margin
    const sanitized = sanitizePDFText(rawLine.trim());
    
    if (sanitized) {
      const isHeader = rawLine.startsWith('#') || rawLine.startsWith('===') || rawLine.includes('SUMMARY') || rawLine.includes('BREAKDOWN');
      const fontSize = isHeader ? 12 : 9;
      const maxLineLength = isHeader ? 75 : 95;
      
      const words = sanitized.split(' ');
      let currentLine = '';
      
      for (const word of words) {
        if ((currentLine + word).length > maxLineLength) {
          streamContent += `BT /F1 ${fontSize} Tf 50 ${y} Td (${currentLine.trim()}) Tj ET\n`;
          y -= (fontSize + 4);
          currentLine = word + ' ';
          if (y < 60) break;
        } else {
          currentLine += word + ' ';
        }
      }
      
      if (currentLine.trim() && y >= 60) {
        streamContent += `BT /F1 ${fontSize} Tf 50 ${y} Td (${currentLine.trim()}) Tj ET\n`;
      }
    }
    y -= 15;
  }

  objects.push(`<< /Length ${streamContent.length} >>\nstream\n${streamContent}endstream`); // 5

  let pdfOutput = '%PDF-1.4\n';
  const offsets = [0];

  for (let i = 0; i < objects.length; i++) {
    offsets.push(pdfOutput.length);
    pdfOutput += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefStart = pdfOutput.length;
  pdfOutput += 'xref\n';
  pdfOutput += `0 ${objects.length + 1}\n`;
  pdfOutput += '0000000000 65535 f \n';
  for (let i = 1; i <= objects.length; i++) {
    pdfOutput += `${offsets[i].toString().padStart(10, '0')} 00000 n \n`;
  }

  pdfOutput += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return new Blob([pdfOutput], { type: 'application/pdf' });
}

function sanitizePDFText(text: string): string {
  return text
    .replace(/[\\()]/g, '') // remove parentheses and backslashes
    .replace(/[^a-zA-Z0-9 .,:;!?_\-+=/<>@#$%&*]/g, ' ');
}

/**
 * Extracts human-readable text from raw PDF streams or text content
 */
export function extractCleanTextFromContent(raw: string, orgName: string = 'CloudSecure Enterprise'): string {
  if (!raw) return '';
  if (raw.includes('%PDF') || (raw.includes('stream') && raw.includes('Tj'))) {
    const matches = raw.match(/\(([\s\S]*?)\)\s*Tj/g);
    if (matches && matches.length > 0) {
      const extracted = matches
        .map((m) => {
          const text = m.replace(/^\(/, '').replace(/\)\s*Tj$/, '').trim();
          return text.replace(/\\([()\\])/g, '$1');
        })
        .filter((line) => !line.startsWith('----------------') && !line.includes('Generated by') && line.length > 0)
        .map((line) => line.replace(/Acme Corp(oration)?/gi, orgName).replace(/Acme/gi, orgName))
        .join('\n');
      if (extracted.trim().length > 0) {
        return extracted;
      }
    }
    return '[Binary PDF Artifact - SHA-256 Verified Compliance Dossier. Click Download to inspect native document.]';
  }
  return raw
    .replace(/Acme Corp(oration)?/gi, orgName)
    .replace(/Acme/gi, orgName);
}

/**
 * Open a styled HTML Printable Report in a new window with automatic print dialog
 */
export function openPrintableReport(title: string, framework: string, content: string, orgName: string = 'CloudSecure Enterprise') {
  const printWindow = window.open('', '_blank', 'width=850,height=900');
  if (!printWindow) return;

  const cleanContent = extractCleanTextFromContent(content)
    .replace(/Acme Corp(oration)?/gi, orgName)
    .replace(/Acme AI-Compliance/gi, `${orgName} AI-Compliance`);

  const formattedHtml = `
<!DOCTYPE html>
<html>
<head>
  <title>${title} - AI Compliance Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.5;
      color: #0f172a;
      padding: 40px;
      margin: 0;
    }
    .header {
      border-bottom: 2px solid #059669;
      padding-bottom: 20px;
      margin-bottom: 25px;
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
    }
    .title {
      font-size: 22px;
      font-weight: 700;
      color: #0f172a;
      margin: 0 0 6px 0;
    }
    .subtitle {
      font-size: 13px;
      color: #64748b;
      margin: 0;
    }
    .badge {
      background: #ecfdf5;
      color: #047857;
      border: 1px solid #a7f3d0;
      padding: 4px 10px;
      border-radius: 9999px;
      font-size: 11px;
      font-weight: 600;
    }
    .content-box {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 20px;
      font-size: 13px;
      white-space: pre-wrap;
      font-family: monospace;
      color: #334155;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      display: flex;
      justify-content: space-between;
      font-size: 11px;
      color: #94a3b8;
    }
    .signature-block {
      margin-top: 40px;
      padding-top: 20px;
      display: flex;
      justify-content: space-between;
    }
    .sig-line {
      width: 220px;
      border-top: 1px solid #94a3b8;
      padding-top: 5px;
      font-size: 11px;
      color: #475569;
    }
    @media print {
      body { padding: 20px; }
      button { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1 class="title">${title}</h1>
      <p class="subtitle">Organization: ${orgName} &bull; Scope: ${framework}</p>
      <p class="subtitle">Generated: ${new Date().toLocaleDateString()} via AI Compliance Engine</p>
    </div>
    <div class="badge">AUDITOR ATTESTED</div>
  </div>

  <div class="content-box">
${cleanContent}
  </div>

  <div class="signature-block">
    <div class="sig-line">
      <strong>Compliance Officer</strong><br>
      Alex Rivera (Head of GRC)
    </div>
    <div class="sig-line">
      <strong>Lead External Auditor</strong><br>
      KPMG LLP / BSI Group
    </div>
  </div>

  <div class="footer">
    <span>${orgName} Compliance &bull; SOC 2 / ISO 27001 / NIST CSF</span>
    <span>Page 1 of 1</span>
  </div>

  <script>
    window.onload = function() {
      setTimeout(() => { window.print(); }, 400);
    }
  </script>
</body>
</html>
`;

  printWindow.document.open();
  printWindow.document.write(formattedHtml);
  printWindow.document.close();
}
