function sanitizePDFText(text) {
  return text
    .replace(/[\\()]/g, '')
    .replace(/[^a-zA-Z0-9 .,:;!?_\-+=/<>@#$%&*]/g, ' ')
    .slice(0, 95);
}

function generateSimplePDF(title, lines) {
  const objects = [];
  
  objects.push('<< /Type /Catalog /Pages 2 0 R >>'); // 1
  objects.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>'); // 2
  objects.push('<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 595.28 841.89] /Contents 5 0 R >>'); // 3
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'); // 4

  let streamContent = `BT /F1 16 Tf 50 800 Td (${sanitizePDFText(title)}) Tj ET\n`;
  streamContent += `BT /F1 10 Tf 50 780 Td (Generated by Acme AI-Compliance Platform - Confidential) Tj ET\n`;
  streamContent += `BT /F1 10 Tf 50 765 Td (------------------------------------------------------------------------------------------------) Tj ET\n`;

  let y = 745;
  for (const rawLine of lines) {
    if (y < 60) break;
    const sanitized = sanitizePDFText(rawLine.trim());
    if (sanitized) {
      const isHeader = rawLine.startsWith('#') || rawLine.startsWith('===') || rawLine.includes('SUMMARY') || rawLine.includes('BREAKDOWN');
      const fontSize = isHeader ? 12 : 9;
      streamContent += `BT /F1 ${fontSize} Tf 50 ${y} Td (${sanitized}) Tj ET\n`;
    }
    y -= 15;
  }

  // NOTE: According to PDF spec, the stream content MUST be followed immediately by \nendstream. 
  // Let's make sure length is calculated correctly.
  // The string length in JavaScript is the number of UTF-16 code units. Since we sanitized to ASCII, this is exactly the byte length.
  objects.push(`<< /Length ${streamContent.length} >>\nstream\n${streamContent}endstream`); // 5

  let pdfOutput = '%PDF-1.4\n';
  const offsets = [0];

  for (let i = 0; i < objects.length; i++) {
    offsets.push(pdfOutput.length);
    pdfOutput += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefStart = pdfOutput.length;
  pdfOutput += 'xref\n';
  pdfOutput += `0 ${objects.length + 1}\n`;
  pdfOutput += '0000000000 65535 f \n';
  for (let i = 1; i <= objects.length; i++) {
    pdfOutput += `${offsets[i].toString().padStart(10, '0')} 00000 n \n`;
  }

  pdfOutput += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return pdfOutput;
}

require('fs').writeFileSync('test2.pdf', generateSimplePDF("Test Title", ["Testing", "1 2 3"]));
