const title = "Hello World";
const lines = ["Line 1", "Line 2"];
  const pdfLines = [
    '%PDF-1.4',
    '1 0 obj',
    '<< /Type /Catalog /Pages 2 0 R >>',
    'endobj',
    '2 0 obj',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    'endobj',
    '3 0 obj',
    '<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 595.28 841.89] /Contents 5 0 R >>',
    'endobj',
    '4 0 obj',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    'endobj',
  ];

  function sanitizePDFText(text) {
    return text
      .replace(/[\\()]/g, '') // remove parentheses and backslashes
      .replace(/[^a-zA-Z0-9 .,:;!?_\-+=/<>@#$%&*]/g, ' ')
      .slice(0, 95);
  }

  let streamContent = 'BT /F1 16 Tf 50 800 Td (' + sanitizePDFText(title) + ') Tj ET\n';
  streamContent += 'BT /F1 10 Tf 50 780 Td (Generated by Acme AI-Compliance Platform - Confidential) Tj ET\n';
  streamContent += 'BT /F1 10 Tf 50 765 Td (------------------------------------------------------------------------------------------------) Tj ET\n';

  let y = 745;
  for (const rawLine of lines) {
    if (y < 60) break; 
    const sanitized = sanitizePDFText(rawLine.trim());
    if (sanitized) {
      const isHeader = rawLine.startsWith('#') || rawLine.startsWith('===') || rawLine.includes('SUMMARY') || rawLine.includes('BREAKDOWN');
      const fontSize = isHeader ? 12 : 9;
      streamContent += `BT /F1 ${fontSize} Tf 50 ${y} Td (${sanitized}) Tj ET\n`;
    }
    y -= 15;
  }

  const streamLength = streamContent.length;
  pdfLines.push('5 0 obj');
  pdfLines.push(`<< /Length ${streamLength} >>`);
  pdfLines.push('stream');
  pdfLines.push(streamContent);
  pdfLines.push('endstream');
  pdfLines.push('endobj');

  const body = pdfLines.join('\n') + '\n';
  const xrefStart = body.length;

  const pdfOutput = `${body}xref\n0 6\n0000000000 65535 f \n0000000009 00000 n \n0000000058 00000 n \n0000000115 00000 n \n0000000227 00000 n \n0000000298 00000 n \ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

require('fs').writeFileSync('test.pdf', pdfOutput);
